#!/bin/sh

tput bold
echo -e "\e[1;34mCopy xfce4 terminal color schemes...\e[1;37m";
mkdir -p /home/plr/.local/share/xfce4/terminal/colorschemes/
sudo cp -R themes/* /home/plr/.local/share/xfce4/terminal/colorschemes/






