#!/bin/bash


# Install Necessary Packages
sudo apt install slick-greeter lightdm-settings -y

# Backup  Lightdm-gtk-greeter configs
sudo mv /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf.bak
sudo mv /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.bak

# Copy Slick-greeter config
sudo cp config/slick-greeter.conf /etc/lightdm/

# Copy User Images
sudo cp -rf lightdm-images /usr/share/
 
# Copy and Replace 50-slick-greeter.conf 
sudo cp -if 50-slick-greeter.conf /usr/share/lightdm/lightdm.conf.d/










