#!/bin/bash
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

tput setaf 3;
echo "################################################################"
echo "Install Ueberzug from source"
echo "################################################################"
echo;tput sgr0

# Install Ueberzug Dependencies
sudo apt install libxext-dev libx11-dev -y

cd ueberzug-files
sudo python3 setup.py install

tput setaf 11;
echo "################################################################"
echo "Stardict-oald Packages has been installed"
echo "################################################################"
echo;tput sgr0

